# Generated by Django 3.2.7 on 2021-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('age', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Edad')),
                ('phone', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('cur', models.CharField(max_length=18, verbose_name='CURP')),
                ('rfc', models.CharField(max_length=12, verbose_name='RFC')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('cedula', models.CharField(max_length=10, verbose_name='cedula')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
    ]
