# Generated by Django 3.2.7 on 2021-09-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio')),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('rfc', models.CharField(max_length=12, verbose_name='RFC')),
                ('ext', models.CharField(max_length=1, verbose_name='No. Exterior')),
                ('int', models.CharField(max_length=10, verbose_name='No. Interior')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
