# Generated by Django 3.2.7 on 2021-09-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso'),
        ),
    ]
