# Generated by Django 3.2.7 on 2021-09-28 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_direction_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cite',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.direction', verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='ext',
            field=models.CharField(max_length=10, verbose_name='No. Exterior'),
        ),
    ]
