# Generated by Django 3.2.7 on 2021-09-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210928_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cite',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.direction', verbose_name='Dirección'),
            preserve_default=False,
        ),
    ]
