# Generated by Django 3.2.7 on 2021-09-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diagnosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
    ]
