# Generated by Django 3.2.7 on 2021-09-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_diagnosis_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=100, verbose_name='Dieta')),
                ('date', models.DateTimeField()),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic', verbose_name='Médico')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Dieta',
                'verbose_name_plural': 'Dietas',
            },
        ),
    ]
