# Generated by Django 3.2.7 on 2021-09-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_record_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='diet',
            field=models.CharField(max_length=100, verbose_name='Dieta'),
        ),
    ]
